export const authTypes = {
	USER_LOADED:"USER_INFO_LOADED",
	USER_LOADING:"USER_INFO_LOADING",
	AUTH_ERROR:"AUTH_ERROR",
	LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
	LOGIN_FAIL:"USER_LOGIN_FAIL",
	LOGOUT_SUCCESS:"USER_LOGOUT_SUCCESS",
	REGISTER_SUCESS:"USER_REGISTER_SUCESS",
	REGISTER_FAIL:"USER_REGISTER_FAIL"
}